name: .NET Core Deploy to IIS

on:
  push:
    branches:
      - main
  workflow_dispatch: 


jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.405
    

    - name: dotnet publish 
      run: |
        dotnet publish -o output

    - run: ls -lrth output

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: ./dotnetapp-devsecops-demo/output/**
        if-no-files-found: error

    # - name: Deploy to IIS
    #   run: |
    #     iisreset /stop
    #     Copy-Item ./dotnetapp-devsecops-demo/* C:/inetpub/wwwroot/dotnetapp-devsecops-demo -Recurse -Force
    #     iisreset /start
    
    # - name: Curl the website as a smoke test
    #   run: curl http://localhost/dotnetcore-webapp

    # - name: Run Web Test
    #   run: |
    #     dotnet build --configuration Release .\dotnet-core-webapp.webtest
    #     cd .\dotnet-core-webapp.webtests
    #     dotnet test